version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: start-process.sh
      timeout: 20
      runas: ec2-user
  # ApplicationStop:
  #   - location: kill-process.sh
  #     timeout: 20
  #     runas: ec2-user
      # AfterInstall:
  #   - location: start-process.sh
  #     timeout: 20
  #     runas: ec2-user