version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      # - chmod +x gradlew
      # - wget -c https://services.gradle.org/distributions/gradle-6.2.2-all.zip
      # - unzip  gradle-6.2.2-all.zip -d /opt
      # - ln -s /opt/gradle-6.2.2 /opt/gradle
      # - printf "export GRADLE_HOME=/opt/gradle\nexport PATH=\$PATH:\$GRADLE_HOME/bin\n" > /etc/profile.d/gradle.sh
      # - sudo chmod +x /etc/profile.d/gradle.sh
      # - source /etc/profile.d/gradle.sh
      # - gradle -v
      # - export PATH=$PATH:/opt/gradle-6.2.2/bin
      # - gradle -v
      - echo Nothing to do in the pre_build phase...
      - yum install java-17-amazon-corretto-devel -y
      - java -version
      - ls -l /usr/lib/jvm/
      - export JAVA_HOME = /usr/lib/jvm/java-17-amazon-corretto-devel/
      - java -version
      # - sudo update-alternatives --set java /usr/lib/jvm/java-17-amazon-corretto.aarch64/bin/java
      - echo $PATH
      - ls -l /usr/lib/jvm/
  build:
    commands:
      - gradle build
      # - sudo su
      # - ./gradlew build
      # - gradlew build
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes