# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "test_ssh" ]

jobs:

  continuous-integration:
    if: github.ref == 'refs/heads/test_ssh'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: gradle build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@test_ssh
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "build/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
  continuous-integration-qa:
    if: github.ref == 'refs/heads/qa'
    runs-on: [self-hosted,pims-qa]
    steps:
    - uses: actions/checkout@v3
    - name: gradle install
      run: export PATH=$PATH:/opt/gradle/gradle-6.2.2/bin
    - name: Build with Gradle
      run: export PATH=$PATH:/opt/gradle/gradle-7.4.2/bin;gradle build
    
  continuous-deployment:
      runs-on: [self-hosted,pims-demo]
      needs: [continuous-integration]
      steps:
       # Step 1
        - name: remove existing execution file
          run: cd /home/ec2-user/actions-runner/pims/sample_java/sample_java; rm execution.sh
        - name: create new execution file
          run: echo 'cd /home/ec2-user/actions-runner/pims/sample_java/sample_java/build/libs' >> execution.sh
        - name: Added execution command to file
          run: echo 'java -jar myapp.jar' >> execution.sh
        - name: Stop the service
          run: sudo systemctl stop sample
        - name: Run the java service
          run: cd /home/ec2-user/actions-runner/pims/sample_java/sample_java;chmod u+x execution.sh;sudo systemctl daemon-reload;sudo systemctl enable sample;sudo systemctl start sample
  continuous-deployment-qa:
      runs-on: [self-hosted,pims-qa]
      needs: [continuous-integration-qa]
      steps:
       # Step 1
        - name: remove existing execution file
          run: cd /home/ec2-user/actions-runner/pims/sample_java/sample_java; rm execution.sh
        - name: create new execution file
          run: echo 'cd /home/ec2-user/actions-runner/pims/sample_java/sample_java/build/libs' >> execution.sh
        - name: Added execution command to file
          run: echo 'java -jar myapp.jar' >> execution.sh
        - name: Stop the service
          run: sudo systemctl stop sample
        - name: Run the java service
          run: cd /home/ec2-user/actions-runner/pims/sample_java/sample_java;chmod u+x execution.sh;sudo systemctl daemon-reload;sudo systemctl enable sample;sudo systemctl start sample
