# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  continuous-integration:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: gradle install
      run: export PATH=$PATH:/opt/gradle/gradle-6.2.2/bin
    - name: Build with Gradle
      run: export PATH=$PATH:/opt/gradle/gradle-7.4.2/bin;gradle build
      
  continuous-deployment:
      runs-on: self-hosted
      needs: [continuous-integration]
      if: github.ref == 'refs/heads/master'
      steps:
       # Step 1
        - name: Stop the service
          run: sudo systemctl stop sample
        - name: Run the java service
          run: cd /home/ec2-user/actions-runner/_work/sample_java/sample_java;chmod u+x execution.sh;sudo systemctl daemon-reload;sudo systemctl enable sample;sudo systemctl start sample
